export const arr = [
    "Vowel Count",
      "Even or Odd",
      "Get the Middle Character",
      "Opposite number",
      "Mumbling",
      "You're a square!",
      "Disemvowel Trolls",
      "Highest and Lowest",
      "Exes and Ohs",
      "Square Every Digit",
      "Shortest Word",
      "Complementary DNA",
      "Descending Order",
      "Sum of positive",
      "Isograms",
      "List Filtering",
      "Find the smallest integer in the array",
      "Sum of two lowest positive integers",
      "Growth of a Population",
      "String repeat",
      "Is this a triangle?",
      "Find the next perfect square!",
      "Credit Card Mask",
      "Sum of odd numbers",
      "Find the divisors!",
      "Return Negative",
      "Remove First and Last Character",
      "Remove String Spaces",
      "Convert boolean values to strings 'Yes' or 'No'.",
      "Convert a Number to a String!",
      "Basic Mathematical Operations",
      "Sum of the first nth term of Series",
      "Keep Hydrated!",
      "Century From Year",
      "Beginner - Lost Without a Map",
      "Reversed Strings",
      "String ends with?",
      "Do I get a bonus?",
      "Abbreviate a Two Word Name",
      "DNA to RNA Conversion",
      "Counting sheep...",
      "Ones and Zeros",
      "A Needle in the Haystack",
      "Remove the minimum",
      "Convert number to reversed array of digits",
      "Make a function that does arithmetic!",
      "Regular Ball Super Ball",
      "Make them bark!",
      "Add property to every object in array",
      "FIXME: Get Full Name",
      "Grasshopper - Summation",
      "Jenny's secret message",
      "Function 1 - hello world",
      "Count the Monkeys!",
      "Are You Playing Banjo?",
      "Find the capitals",
      "Plural",
      "Drink about",
      "Leonardo Dicaprio and Oscars",
      "Switch/Case - Bug Fixing #6",
      "Sentence Smash",
      "If you can't sleep, just count sheep!!",
      "Double Char",
      "Unfinished Loop - Bug Fixing #1",
      "Sum of numbers"
]